defaults:
  - base

micro_batch_size_per_gpu: 1
ppo_mini_batch_size: 16

system:
  CUDA_VISIBLE_DEVICES: "0,1,2,3"

actor_rollout_ref:
  rollout:
    response_length: 128
    tensor_model_parallel_size: 4
    gpu_memory_utilization: 0.40 # for A100
    val_kwargs:
      do_sample: True
      temperature: 0.5

trainer:
  experiment_name: lbat-baseline
  n_gpus_per_node: 4
  print_token_advantages: True

agent_proxy:
  max_turn: 20
  max_actions_per_turn: 1

es_manager:
  train:
    env_configs:
      tags: ["LBAT"]
  val:
    env_groups: 8
    env_configs:
      tags: ["LBAT"]
      n_groups: [8]

# for accel
accel:
  enabled: false


