defaults:
  - base

system:
  CUDA_VISIBLE_DEVICES: "0,1,2,3" # for testing  

actor_rollout_ref:
  rollout:
    response_length: 128
    tensor_model_parallel_size: 4
    val_kwargs:
      do_sample: True
      temperature: 0.5 # enabling randomness in evaluation 
 
trainer:
  experiment_name: underspecified-bandit-base
  n_gpus_per_node: 4

agent_proxy:
  max_turn: 20
  # max_turn: 5 # for testing
  max_actions_per_turn: 1 # how many actions can be output at most in a single turn

es_manager:
  train:
    env_configs:
      tags: ["UnderspecifiedBandit"] # BanditGeneralizationNoThink
  val:
    env_groups: 8
    env_configs:
      tags: ["UnderspecifiedBandit"]
      n_groups: [8]

# for accel
accel:
  enabled: false