model_name: gpt-4
model_type: openai_api_models
base_model_name: gpt-4

# No use for gpt models
model_max_length: 131072

# only used for making savefile directory
model_name_summary: gpt-4/gpt-4

# tokenizer name, used for tokenizer_separator
tokenizer_name: gpt-4

# used for saving files
save_file_name: gpt-4

finetuned_tokenizer: False