model_name: gpt-4o-mini
model_type: openai_api_models
base_model_name: gpt-4o-mini

# No use for gpt models
model_max_length: 131072

# only used for making savefile directory
model_name_summary: gpt-4o-mini/gpt-4o-mini

# tokenizer name, used for tokenizer_separator
tokenizer_name: gpt-4o-mini